version: "3.7"

services:

  # app_proxy:
  #   environment:
  #     # The format here is: <app-id>_<docker-service-name>_1
  #     APP_HOST: pluto-nostrudel_server_1
  #     APP_PORT: 80
    
  server:
    image: ghcr.io/hzrd149/nostrudel:master
    init: true
    ports:
      - "4999:80"
