version: "3.7"

services:
  # app_proxy:
  #   environment:
  #     # The format here is: <app-id>_<docker-service-name>_1
  #     APP_HOST: pluto-teslamate_teslamate-1
  #     APP_PORT: 4000

  teslamate:
    image: teslamate/teslamate:latest
    restart: always
    user: "1000:1000"
    environment:
      - ENCRYPTION_KEY=N0TS3CUR3!69 #insert a secure key to encrypt your Tesla API tokens
      - DATABASE_USER=teslamate
      - DATABASE_PASS=N0TS3CUR3!69 #insert your secure database password!
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=database
      - MQTT_HOST=mosquitto
    ports:
      - 4069:4000
    volumes:
      - ./import:/opt/app/import
    cap_drop:
      - all

  database:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=teslamate
      - POSTGRES_PASSWORD=N0TS3CUR3!69 #insert your secure database password!
      - POSTGRES_DB=teslamate
    volumes:
      - ./data/teslamate-db:/var/lib/postgresql/data

  grafana:
    image: teslamate/grafana:latest
    restart: always
    user: "1000:1000"
    environment:
      - DATABASE_USER=teslamate
      - DATABASE_PASS=N0TS3CUR3!69 #insert your secure database password!
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=database
    ports:
      - 4070:3000
    volumes:
      - ./data/teslamate-grafana-data:/var/lib/grafana

  mosquitto:
    image: eclipse-mosquitto:2
    restart: always
    command: mosquitto -c /mosquitto-no-auth.conf
    volumes:
      - ./data/mosquitto-conf:/mosquitto/config
      - ./data/mosquitto-data:/mosquitto/data